### ISSUE TITLE
Add a minimal client interface

### ISSUE THREAD

**Issue by clintonskitson** [emccode/libstorage#102]
It might be handy to have a NewClientMinimal function in /client that allows a system that does not wish to perform OS/integration capabilities to leverage the library. 

Assuming it would be something like this. But it looks like this is still sending over headers of discovered devices, etc.

```
// NewClientMinimal returns a new libStorage client.
func NewClientMinimal(config gofig.Config) (types.Client, error) {

	if config == nil {
		var err error
		if config, err = apicnfg.NewConfig(); err != nil {
			return nil, err
		}
	}

	if s := config.GetScope(); s != "" {
		config = config.Scope(fmt.Sprintf("%s.%s", s, types.ConfigClient))
	}
	config = config.Scope(types.ConfigClient)

	var (
		c   *client
		err error
	)

	c = &client{ctx: context.Background().WithConfig(config), config: config}
	c.ctx = c.ctx.WithClient(c)

	if config.IsSet(types.ConfigService) {
		c.ctx = c.ctx.WithServiceName(config.GetString(types.ConfigService))
	}

	storageDriverName := config.GetString(types.ConfigStorageDriver)
	if c.sd, err = registry.NewStorageDriver(storageDriverName); err != nil {
		return nil, err
	}
	if err = c.sd.Init(c.ctx, config); err != nil {
		return nil, err
	}
	if papi, ok := c.sd.(types.ProvidesAPIClient); ok {
		c.api = papi.API()
	}
	c.ctx = c.ctx.WithContextSID(types.ContextStorageDriver, storageDriverName)
	c.ctx.Info("storage driver initialized")

	c.ctx.Info("created libStorage client")
	return c, nil
}
```

**Comment by akutz** [comment]
Hi @clintonskitson,

A minimal client exists today, it's called the `APIClient` and the implementation of it is at [`./api/client/client.go`](https://github.com/emccode/libstorage/blob/master/api/client/client.go).

But what you're *really* trying to find I think is a client that suits your needs exactly the way you want for your use case at the moment. :)

And that's fine; it's just not feasible. There are three levels of client:

Level | Client | Description
--------|---------|----------------
0 | [APIClient](https://github.com/emccode/libstorage/blob/master/api/client) | This is the lowest-level  client there is -- it's for directly accessing the server's API resources. 
1 | [libStorage Storage Driver](https://github.com/emccode/libstorage/blob/master/drivers/storage/libstorage/storage) | Despite the name, this is the client that does most of the heavy lifting -- it's just hidden inside a type that satisfies the `StorageDriver` interface. This client also acts as the `ExecutorCLI`.
2 | [libStorage Client](https://github.com/emccode/libstorage/blob/master/client) | The libStorage client is the top-level client that is returned when `libstorage.Dial` or `libstorage.New` are invoked. This client is responsible for injecting itself into the `ctx` and providing all downstream consumers on the client with access to an OS, Integration, and Storage driver as well as access to the Executor CLI. Additionally, this client also provides direct access to the underlying, above clients.

I wasn't a fan of creating the helper server code placed in the main server package. I still think it's a bad idea to put anything that's essentially utility/helper bits inside the core library. Instead a series of utility libraries should be built around a stable core.

To your original use case, what you're actually wanting to do is replace the second client listed above, the `libStorage Storage Driver` client, out from underneath the `libStorage Client`. That can be done today by simply building the libStorage client code with one or more additional `StorageDriver` imports (since the only `StorageDriver` imported on the client-side is `./drivers/storage/libstorage/storage`). If a version of the libStorage client was built that imported the `ScaleIO` driver the property `libstorage.storage.driver` could be set to `scaleio` and the **Level 2** `libStorage Client` would not create the **Level 1** `libStorage Storage Driver Client` or the **Level 0** `APIClient`.

What would have to happen that the **Level 2** `libStorage Client` doesn't do today is for it to detect that it's not using the standard **Level 1** `libStorage Storage Driver Client` and elect to only load the registered `StorageDriver` and omit the steps for loading the OS or Integration drivers.

While I'll fulfill the outlined workflow bypass, that's the limit of where I'm willing to take this. In a future release I'm seriously considering pulling the utility server classes out anyway, leaving only the `Serve` command. At least pulling them out of the `./api/server` package. They simply do not belong there -- just as a minimal client proposal doesn't belong in a core package either.

I'm thinking a folder at the root called `helpers` should be created, and client and server helper logic/packages can be relocated/created there.

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm closing this issue as I believe it's been handled via discussion and all that is lacking is documentation on how to leverage existing resources inside the package to provide the requested feature.
