### ISSUE TITLE
Executor Download not comparing MD5 sum properly

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/libstorage#306]
The executor download logic in https://github.com/emccode/libstorage/blob/master/drivers/storage/libstorage/libstorage_client.go#L147 is comparing a md5 hex-encoded string value to base64-encoded value sent by the lss server in line https://github.com/emccode/libstorage/blob/master/api/server/router/executor/executor_routes.go#L70.

This means that test (in the former link above) will always fail.  The client libStorage driver should further encode its calculated md5 as a base64 here  https://github.com/emccode/libstorage/blob/master/drivers/storage/libstorage/libstorage_client.go#L188.

**Comment by akutz** [comment]
Hi @vladimirvivien,

Thanks for finding this! Care to submit a PR?

**Comment by akutz** [comment]
Hi @vladimirvivien,

Wait, actually I'm not sure this is a bug. The `Content-MD5` isn't the value the client uses as the checksum.

**Comment by akutz** [comment]
FWIW @vladimirvivien, the only reason the Content-MD5 header is base-64 encoded is because of the header's [RFC](https://tools.ietf.org/html/rfc1864). However, as I said, it's not what is used. The client uses the JSON from the call that inspects the executor info. The headers are returned along with the actual executor binary, not the info.

**Comment by vladimirvivien** [comment]
@akutz ok I see that now that you pointed it out it is comparing it with the checksum from the JSON value, not the value from the executorInspect call.
